Page({
  data: {
    isDark: false,
    currentWeek: 3,
    termStartDate: '2026-02-23',
    sectionTimes: {
      1: ['08:00', '08:45'],
      2: ['08:55', '09:40'],
      3: ['10:00', '10:45'],
      4: ['10:55', '11:40'],
      5: ['14:00', '14:45'],
      6: ['14:55', '15:40'],
      7: ['16:00', '16:45'],
      8: ['16:55', '17:40'],
      9: ['19:00', '19:45'],
      10: ['19:55', '20:40'],
      11: ['20:50', '21:35'],
    },
    settings: {
      showWeekend: false,
      showOtherWeek: true,
      cellHeight: 120,
      background: {
        url: '',
        opacity: 1,
        blur: 0,
      },
    },
    courses: [
      {
        id: 'course-1',
        courseName: '高等数学',
        teacher: '张老师',
        place: '教学楼 A101（实验室）',
        weekday: 1,
        sections: [{ section: 1 }, { section: 2 }],
        weeks: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        id: 'course-2',
        courseName: '大学英语',
        teacher: '李老师',
        place: '二教 203（多媒体教室）',
        weekday: 2,
        sections: [{ section: 3 }, { section: 4 }],
        weeks: [1, 2, 4, 5, 6],
      },
      {
        id: 'course-3',
        courseName: '程序设计基础',
        teacher: '王老师',
        place: '计算机楼 501',
        weekday: 2,
        sections: [{ section: 3 }, { section: 4 }],
        weeks: [3, 7, 8, 9, 10],
      },
      {
        id: 'course-4',
        courseName: '线性代数',
        teacher: '陈老师',
        place: '教学楼 B305',
        weekday: 1,
        sections: [{ section: 5 }, { section: 6 }],
        weeks: [1, 2, 3, 4, 5, 6, 7, 8],
      },
      {
        id: 'course-5',
        courseName: '大学物理',
        teacher: '刘老师',
        place: '理科楼 201',
        weekday: 3,
        sections: [{ section: 1 }, { section: 2 }],
        weeks: [2, 3, 4, 5, 6, 7, 8, 9],
      },
      {
        id: 'course-6',
        courseName: '数据结构',
        teacher: '周老师',
        place: '计算机楼 406',
        weekday: 3,
        sections: [{ section: 7 }, { section: 8 }],
        weeks: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      },
      {
        id: 'course-7',
        courseName: '中国近现代史纲要',
        teacher: '吴老师',
        place: '文科楼 102',
        weekday: 4,
        sections: [{ section: 3 }, { section: 4 }],
        weeks: [1, 2, 3, 4, 5, 6],
      },
      {
        id: 'course-8',
        courseName: '概率论与数理统计',
        teacher: '孙老师',
        place: '教学楼 C208',
        weekday: 4,
        sections: [{ section: 7 }, { section: 8 }],
        weeks: [1, 3, 5, 7, 9, 11, 13, 15],
      },
      {
        id: 'course-9',
        courseName: '软件工程导论',
        teacher: '郑老师',
        place: '实验楼 302',
        weekday: 5,
        sections: [{ section: 1 }, { section: 2 }],
        weeks: [3, 4, 5, 6, 7, 8, 9, 10],
      },
      {
        id: 'course-10',
        courseName: '形势与政策',
        teacher: '黄老师',
        place: '报告厅',
        weekday: 5,
        sections: [{ section: 9 }, { section: 10 }, { section: 11 }],
        weeks: [2, 4, 6, 8],
      },
      {
        id: 'course-11',
        courseName: '移动应用开发',
        teacher: '何老师',
        place: '计算机楼 608',
        weekday: 5,
        sections: [{ section: 9 }, { section: 10 }, { section: 11 }],
        weeks: [3, 5, 7, 9, 11],
      },
      {
        id: 'course-12',
        courseName: '体育',
        teacher: '赵老师',
        place: '体育馆（东区）',
        weekday: 6,
        sections: [{ section: 5 }, { section: 6 }],
        weeks: [3, 4, 5, 6],
      },
      {
        id: 'course-13',
        courseName: '创新创业实践',
        teacher: '许老师',
        place: '创业学院 101',
        weekday: 7,
        sections: [{ section: 3 }, { section: 4 }],
        weeks: [3, 6, 9, 12],
      },
    ],
  },

  handleCourseTap(event) {
    console.log('courseTap:', event.detail)
  },

  handleWeekendDetected(event) {
    console.log('weekendDetected:', event.detail)
  },

  toggleTheme() {
    this.setData({
      isDark: !this.data.isDark,
    })
  },
})
